package eu.cqse.teamscale.report.testwise.model.builder;

import eu.cqse.teamscale.report.testwise.model.TestDetails;
import eu.cqse.teamscale.report.testwise.model.TestExecution;
import eu.cqse.teamscale.report.testwise.model.TestInfo;

/** Generic container of all information about a specific test including details, execution info and coverage. */
public class TestInfoContainer {

	/** The uniformPath of the test (see TEST_IMPACT_ANALYSIS_DOC.md for more information). */
	private final String uniformPath;

	/** The test details of this test. */
	private TestDetails details;

	/** Information about the execution result of this test. */
	private TestExecution execution;

	/** Coverage generated by this test. */
	private TestCoverageBuilder coverage;

	/** Constructor. */
	/* package */ TestInfoContainer(String uniformPath) {
		this.uniformPath = uniformPath;
	}

	/** @see #uniformPath */
	public String getUniformPath() {
		return uniformPath;
	}

	/** Returns true if there is no coverage for the test yet. */
	public boolean isEmpty() {
		return coverage.isEmpty();
	}

	/** @see #details */
	public void setDetails(TestDetails details) {
		this.details = details;
	}

	/** @see #execution */
	public void setExecution(TestExecution execution) {
		this.execution = execution;
	}

	/** @see #coverage */
	public void setCoverage(TestCoverageBuilder coverage) {
		this.coverage = coverage;
	}

	TestInfo build() {
		if (coverage == null) {
			System.err.println("No coverage for test '" + uniformPath + "'");
			return null;
		}
		TestInfo testInfo;
		if (execution != null) {
			testInfo = new TestInfo(uniformPath, details.sourcePath, details.content,
					execution.getDurationSeconds(),
					execution.getResult(), execution.getMessage());
		} else {
			testInfo = new TestInfo(uniformPath, details.sourcePath, details.content, null, null, null);
		}
		testInfo.paths.addAll(coverage.getPaths());
		return testInfo;
	}
}
